name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 199.241.138.219
          username: pad
          password: R0b0timut!
          port: 22
          script: cd /home/pad/pustaka-portal && sh deploy.sh && openssl rand -hex 20 > .version
